"use client";

import React from "react";
import { Info } from "lucide-react";

interface DetectionBadgeProps {
  score: number; // 0 to 1
}

export function DetectionBadge({ score }: DetectionBadgeProps) {
  let colorClass = "";
  let label = "";

  if (score <= 0.15) {
    colorClass = "bg-green-100 text-green-700 border-green-200";
    label = "Safe";
  } else if (score <= 0.4) {
    colorClass = "bg-amber-100 text-amber-700 border-amber-200";
    label = "Caution";
  } else {
    colorClass = "bg-red-100 text-red-700 border-red-200";
    label = "Risk";
  }

  const percentage = Math.round(score * 100);

  return (
    <div className="group relative flex items-center">
      <div className={`flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold border ${colorClass}`}>
        <span className="relative flex h-2 w-2">
          <span className={`animate-ping absolute inline-flex h-full w-full rounded-full opacity-75 ${score <= 0.15 ? 'bg-green-400' : score <= 0.4 ? 'bg-amber-400' : 'bg-red-400'}`}></span>
          <span className={`relative inline-flex rounded-full h-2 w-2 ${score <= 0.15 ? 'bg-green-500' : score <= 0.4 ? 'bg-amber-500' : 'bg-red-500'}`}></span>
        </span>
        <span>{percentage}% AI</span>
        <span className="opacity-75 font-normal ml-0.5 border-l border-current pl-1.5">{label}</span>
      </div>
      
      {/* Tooltip */}
      <div className="absolute right-0 top-full mt-2 w-48 p-2 bg-slate-800 text-slate-100 text-xs rounded shadow-lg opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all z-10">
        <div className="flex gap-1.5 mb-1">
          <Info className="w-3.5 h-3.5 shrink-0" />
          <span className="font-semibold">AI Detection Score</span>
        </div>
        <p className="text-slate-300">
          Estimated probability that the text was generated by AI. Lower is better.
        </p>
      </div>
    </div>
  );
}
